### ISSUE TITLE
GSCXScanner fatal error: 'abseil/absl/strings/str_cat.h' file not found

### ISSUE THREAD

**Issue by marybm-dev** [google/GSCXScanner#8]
This error happens when I try to build my app target that uses this pod.
<img width="839" alt="Screenshot 2023-05-17 at 2 51 00 PM" src="https://github.com/google/GSCXScanner/assets/6549791/09185865-20e9-4549-bf07-ea811e8e1845">

I wonder if the issue is that GSCXScanner depends on GTXiLib [v4.0.1](https://github.com/google/GSCXScanner/blob/ba8fca684a11c96c600a1583161dbc6d1c768976/GSCXScanner.podspec#L12) but that library is currently on [v5.1.2](https://github.com/google/GTXiLib/commit/2f396e6d281749cf64bd0e17a55600c305633631) so something seems to have broken along the way.

Repro steps:
1. Create a new Xcode project `GSCXScannerDemo` with SwiftUI on your desktop.
2. In project select the target `GSCXScannerDemo`, right click and select `Duplicate`. Rename to `GSCXScannerDemoCopy`. Close Xcode.
4. Open terminal and `cd ~/Desktop/GSCXScannerDemo` then `pod init`
5. Open `Podfile`
6. In `target 'GSCXScannerDemoCopy' do` add `pod 'GSCXScanner'`
7. Close `Podfile` and in terminal run `pod install`
8. Open `GSCXScannerDemo.xcworkspace`
9. Build and run `GSCXScannerDemo` target - should build no problems.
10. Build and run `GSCXScannerDemoCopy` target - should fail to build target GTXiLib with error `'abseil/absl/strings/str_cat.h' file not found` for  both xml_utils.cc and `nearest_ancestor_relation_resource_id_generator.cc`

**Comment by CooperCorona** [comment]
Hi, can you try removing `use_frameworks!` from all the targets in your Podfile? Or at least from `GSCXScannerDemoCopy`? If that doesn't work, try adding `use_modular_headers!` _before_ your `target` declarations. [use_frameworks! breaks Swift builds in some cases](https://github.com/google/GTXiLib#cocoapods-and-swift). Looks like we need to add that documentation to this project as well. I followed your reproduction steps locally, and when I removed `use_frameworks!`, I was able to build the target. Don't forget to rerun `pod install`.

**Comment by marybm-dev** [comment]
Just confirming that the issue was resolved when I removed `use_frameworks!`
