### ISSUE TITLE
Scanner button doesn't appear in SwiftUI project

### ISSUE THREAD

**Issue by marybm-dev** [google/GSCXScanner#9]
While running the target with GSCXScanner, I don't actually see the "Perform Scan" button or any output in the lldb debugger. 

I also added an inaccessible view to my hierarchy but that doesn't seem to get flagged either. Looking at the project file and the target configuration I can see that libPods-GSCXScannerCopy.a is shown in the Frameworks, Libraries, and Embedded Content. 

<img width="1530" alt="Screenshot 2023-05-18 at 9 37 03 AM" src="https://github.com/google/GSCXScanner/assets/6549791/126f016c-54f8-4929-ab27-52b70754310a">

Maybe this is a UIScene-related bug.

**Comment by CooperCorona** [comment]
The most recent commit _should_ fix this. It changed when Scanner installs itself automatically to account for `UIScene`'s lifecycle. Please update your pods (new CocoaPod releases can take a bit to propagate). You are looking for version 4.0.2.

To test this, add `.accessibilityLabel(Text(""))` to the globe image in the demo app. That should produce an accessibility element without an accessibility label. GSCXScanner should flag that element as having an accessibility issue.

**Comment by marybm-dev** [comment]
Thanks v4.0.2 does appear to have fixed the issue!
